sudo: required
os:
- linux
dist: bionic
branches:
  only:
    - master
jobs:
  include:
    - stage: build
      before_install:
        - sudo apt -y update
        - sudo apt -y install texlive-latex-base texlive-latex-extra poppler-utils imagemagick
      script:
        - pdflatex -interaction=nonstopmode main.tex || echo "failed but whatever"
        - pdflatex -interaction=nonstopmode main.tex || echo "failed but whatever"
        - pdflatex -interaction=nonstopmode main.tex || echo "failed but whatever"
        - mkdir -p output
        - mv main.pdf output/presentation.pdf
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: output
        github_token: $GH_REPO_TOKEN
        on:
          branch: master
